skillbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from skillbook.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='home'),
    path('', include('users.urls', namespace='users')),
    path('', include('skillbook_app.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skillbook_app/urls.py
from django.urls import path
from .views import (
    PostCreatView,
    PostUpdateView,
    PostDeleteView,
    PostCategoryView,
    add_to_like,
    remove_from_like
)

app_name = 'posts'

urlpatterns = [
    path('post-create/', PostCreatView.as_view(), name='post_create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/category/', PostCategoryView.as_view(), name='post_category'),
    path('<int:pk>/add-to-like/', add_to_like, name='add_to_like'),
    path('<int:pk>/remove-from-like/', remove_from_like, name='remove_from_like')
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from users.views import (
    SignInView,
    SignUpView,
    EditProfileView,
    ProfileDetailView,
    ProfileListView,
    ProfileWiseLikedPostView
)

app_name = 'users'

urlpatterns = [
    path('signin/', SignInView.as_view(), name='signin'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('edit/<int:pk>/profile/', EditProfileView.as_view(), name='edit-profile'),
    path('profile/<int:pk>/detail/', ProfileDetailView.as_view(), name='profile'),
    path('curators/', ProfileListView.as_view(), name='curators'),
    path('liked-post/', ProfileWiseLikedPostView.as_view(), name='liked_post'),
]

skillbook_app/models.py
from django.db import models
from django.urls import reverse

from users.models import Profile


class PostCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(PostCategory, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to='post_pics')
    file = models.FileField(upload_to='post_files')
    source_link = models.URLField(max_length=200)
    date_posted = models.DateTimeField(auto_now_add=True, auto_now=False)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')
    liked = models.ManyToManyField(Profile, related_name='liked_posts', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('users:profile', kwargs={'pk': self.author.pk})

templates/base.html
{% load static %}
<!DOCTYPE html>
<!--  This site was created in Webflow. http://www.webflow.com  -->
<!--  Last Published: Sat Mar 21 2020 08:27:12 GMT+0000 (Coordinated Universal Time)  -->
<html data-wf-page="5d6cfc49b15033aac5073b45" data-wf-site="5d6cfc49b150334787073b44">
<head>
  <meta charset="utf-8">
  <title>{% block title %} {% endblock %}</title>
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">
  <link href="{% static 'css/normalize.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/webflow.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/skilbook.webflow.css' %}" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
  <script type="text/javascript">WebFont.load({  google: {    families: ["Lato:100,100italic,300,300italic,400,400italic,700,700italic,900,900italic","Merriweather:300,300italic,400,400italic,700,700italic,900,900italic"]  }});</script>
  <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
  <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
  <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">
  <link href="{% static 'images/webclip.png' %}" rel="apple-touch-icon">
</head>
<body class="body">
  <nav class="navigation">
    <div class="wrap">
      <div class="nav">
        <div class="nav-left">
            <a href="{% url 'home' %}" aria-current="page" class="home_logo w-inline-block w--current">
                <img src="{% static 'images/logo-1.svg' %}" alt="" class="image">
            </a>
          <div class="nav-links">
              <a href="{% url 'home' %}" class="link">Home</a>
              <a href="{% url 'users:curators' %}" class="link">Curators</a>
          </div>
        </div>
        {% if request.user.is_authenticated %}
            <div class="nav-right">
                <a href="{% url 'posts:post_create' %}" class="sign_in w-button">Add a new post</a>
              <div data-w-id="b0ad840d-3d76-01c1-bfbc-59d62871a568" class="profile">
                  {% if request.user.profile.image %}
                    <img src="{{ request.user.profile.image.url }}" alt="" class="profile_avator">
                  {% else %}
                    <img src="{% static 'images/Unknown.png' %}" alt="" class="profile_avator">
                  {% endif %}
                  <img src="{% static 'images/chevron-down.svg' %}" alt="" class="profile_arrow">
                <div class="profile_click_content">
                    <a href="{% url 'users:profile' request.user.profile.pk %}" aria-current="page" class="link_white w--current">Profile</a>
                    <a href="{% url 'posts:post_create' %}" class="link_white">New Post</a>
                    <a href="{% url 'users:edit-profile' request.user.profile.pk %}" class="link_white">Edit Profile</a>
                    <a href="{% url 'users:liked_post' %}" class="link_white">Liked Posts</a>
                    <a href="{% url 'users:logout' %}" class="logged_out">Log Out</a></div>
              </div>
            </div>
        {% else %}
            <div class="nav-right">
                <a href="{% url 'users:signin' %}" class="sign_in w-button">Sign In</a>
                <a href="{% url 'users:signup' %}" class="button w-button">Sign up</a>
            </div>
        {% endif %}
      </div>
    </div>
  </nav>

  {% include 'message.html' %}

  {% block content %}

  {% endblock %}

  <nav class="navigation">
    <div class="wrap">
      <div class="nav">
        <div class="nav-left">
            <a href="#" class="home_logo w-inline-block">
                <img src="{% static 'images/logo-1.svg' %}" alt="" class="image">
            </a>
          <div class="nav-links">
              <a href="{% url 'home' %}" class="link">Home</a>
              <a href="{% url 'users:curators' %}" class="link">Curators</a>
          </div>
        </div>
        {% if not request.user.is_authenticated %}
            <div class="nav-right">
                <a href="{% url 'users:signin' %}" class="sign_in w-button">Sign In</a>
                <a href="{% url 'users:signup' %}" class="button w-button">Sign up</a>
            </div>
        {% endif %}
      </div>
    </div>
  </nav>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.4.1.min.220afd743d.js?site=5d6cfc49b150334787073b44" type="text/javascript" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="{% static 'js/webflow.js' %}" type="text/javascript"></script>
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>
</html>

templates/curators.html
{% load static %}

  <div class="wrap">
    <div class="tags-row">
      <h3 class="tag-title">Top curators</h3>
      <div class="tags-block curators">
          {% for curator in curators_list %}
              <a href="{% url 'users:profile' curator.pk %}" class="curator_link_blog w-inline-block">
                  {% if curator.image %}
                    <img src="{{ curator.image.url }}" alt="" class="avator">
                  {% else %}
                    <img src="{% static 'images/Unknown.png' %}" alt="" class="avator">
                  {% endif %}
                  <h1 class="curator-name">{{ curator.name }}</h1>
                  <p class="curator-bio">{{ curator.bio }}<br></p>
              </a>
          {% endfor %}
      </div>
    </div>
  </div>

templates/home.html
{% extends 'base.html' %}
<title>{% block title %}Home{% endblock %}</title>
{% block content %}
{% load static %}
{% get_media_prefix as MEDIA_URL %}
  <div class="wrap">
    <div class="div-block">
      <div data-w-id="8e04ccf9-aad9-56f7-a5e4-abf16ac65bdf" data-animation-type="lottie" data-src="https://uploads-ssl.webflow.com/5d6cfc49b150334787073b44/5d708aae9b8d7bf1b98a1e42_9065-notifications.json" data-loop="1" data-direction="-1" data-autoplay="1" data-is-ix2-target="0" data-renderer="svg" data-default-duration="2.033333333333333" data-duration="0" class="lottie-animation"></div>
      <h1 class="title">Explore your potentials</h1>
      <h3 class="sub-head">We curate the best Resources to help you learn<a href="https://spreadshare.co/stream/133"><br></a></h3>
    </div>
    <div class="collection">
      {% for post in post_list %}
          <div class="collection-item">
            <a href="{{ post.source_link }}" target="_blank">
                <img src="{{ MEDIA_URL }}{{ post.image }}" sizes="(max-width: 479px) 29vw, (max-width: 991px) 30vw, 290.390625px" alt="" class="post_img">
            </a>
            <h2 class="post_title">{{ post.title }}<br></h2>
            <p class="post_desc">
                {{ post.content|truncatechars:200 }}
            </p>
            {% if request.user.profile in post.liked.all %}
                <a href="{% url 'posts:remove_from_like' post.pk %}">
                  <img src="{% static 'images/heart.png' %}" alt="" class="like_icon">
                </a>
            {% else %}
                <a href="{% url 'posts:add_to_like' post.pk %}">
                  <img src="{% static 'images/heart.svg' %}" alt="" class="like_icon">
                </a>
            {% endif %}
            <a class="submit-button-2 w-button" href="{{ post.file.url }}">Download File</a>
          </div>
      {% endfor %}
    </div>
    {% include 'sources_tags.html' %}
  </div>
  {% include 'subscribe.html' %}
  {% include 'curators.html' %}
{% endblock %}

templates/message.html
<div class=" px-0 pt-3" style="width: 100%">
{% if messages %}
        <div class="messages">
            <ul class="messages p-0 m-0" style="list-style: none;">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                            {% if 'html_safe' in message.tags %}
                              <div class="alert alert-success mx-0" id="publishPost">
                                  <strong>{{ message | safe }}</strong>
                              </div>
                            {%  else %}
                              <div class="alert alert- mx-0" id="publishPost">
                                  <strong>{{ message }}</strong>
                              </div>
                            {% endif %}</li>
                {% endfor %}
            </ul>
        </div>
{% endif %}
</div>

templates/sources_tags.html
<div class="tags-row">
  <h4 class="tag-title">Sources Tags<a href="https://spreadshare.co/tag/16944"><br></a></h4>
  <div class="tags-block">
    {% for category in category_list %}
    <a href="{% url 'posts:post_category' category.pk %}" class="tag_link_block w-inline-block">
      <div class="tag_text">{{ category.name }}</div>
    </a>
    {% endfor %}
  </div>
</div>

templates/subscribe.html
  <div class="section">
    <div class="wrap">
      <div class="newsletter">
        <div class="newsletter_left">
          <h4 class="heading">Subscribe to updates<br></h4>
          <p class="paragraph">Want to get the platform update? Subscribe right now with this form<br></p>
        </div>
        <div class="newsletter-form">
          <div class="form-block w-form">
            <form id="email-form" name="email-form" data-name="Email Form" class="form">
                <label for="email"></label>
                <input type="email" class="newsletter-form-input w-input" maxlength="256" name="email" data-name="Email" placeholder="Enter your email" id="email" required="">
                <input type="submit" value="Subscribe" data-wait="Please wait..." class="submit-button w-button">
            </form>
            <div class="w-form-done">
              <div>Thank you! Your submission has been received!</div>
            </div>
            <div class="w-form-fail">
              <div>Oops! Something went wrong while submitting the form.</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>