skillbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from skillbook.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='home'),
    path('', include('users.urls', namespace='users')),
    path('', include('skillbook_app.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skillbook_app/urls.py
from django.urls import path
from .views import (
    PostCreatView,
    PostUpdateView,
    PostDeleteView,
    PostCategoryView,
    add_to_like,
    remove_from_like
)

app_name = 'posts'

urlpatterns = [
    path('post-create/', PostCreatView.as_view(), name='post_create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/category/', PostCategoryView.as_view(), name='post_category'),
    path('<int:pk>/add-to-like/', add_to_like, name='add_to_like'),
    path('<int:pk>/remove-from-like/', remove_from_like, name='remove_from_like')
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from users.views import (
    SignInView,
    SignUpView,
    EditProfileView,
    ProfileDetailView,
    ProfileListView,
    ProfileWiseLikedPostView
)

app_name = 'users'

urlpatterns = [
    path('signin/', SignInView.as_view(), name='signin'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('edit/<int:pk>/profile/', EditProfileView.as_view(), name='edit-profile'),
    path('profile/<int:pk>/detail/', ProfileDetailView.as_view(), name='profile'),
    path('curators/', ProfileListView.as_view(), name='curators'),
    path('liked-post/', ProfileWiseLikedPostView.as_view(), name='liked_post'),
]

users/models.py
from django.db import models
from django.urls import reverse

from skillbook import settings
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from PIL import Image


class UserProfileManager(BaseUserManager):
    def create_user(self, email, name, password=None):
        """
        Creates and saves a User with the given email, name
         and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            name=name
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class UserProfile(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    name = models.CharField(
        verbose_name='your name',
        max_length=100,
        null=True,
        blank=True
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserProfileManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    designation = models.CharField(max_length=500, null=True, blank=True)
    bio = models.CharField(max_length=500, null=True, blank=True)
    source_bio = models.CharField(max_length=500, null=True, blank=True)
    image = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return f'{self.user.name} Profile'

    def get_absolute_url(self):
        return reverse('users:profile', kwargs={'pk': self.pk})

#     def save(self):
#         super().save()
#
#         img = Image.open(self.image.path)
#
#         if img.height > 300 or img.width > 300:
#             output_size = (300, 300)
#             img.thumbnail(output_size)
#             img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from users.models import UserProfile, Profile


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'text-field w-input',
        'placeholder': 'eg. ******&#x27;'
    }))
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput(attrs={
        'class': 'text-field w-input',
        'placeholder': 'eg. ******&#x27;'
    }))

    class Meta:
        model = UserProfile
        fields = ('name', 'email')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'text-field w-input',
                'placeholder': 'eg. moshfequr rahman',
                'required': True
            }),
            'email': forms.EmailInput(attrs={
                'class': 'text-field w-input',
                'placeholder': 'eg. email@gmail.com'
            }),
        }

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = UserProfile
        fields = ('email', 'password', 'name', 'is_active', 'is_admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('name', 'email', 'designation', 'bio', 'source_bio', 'image')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'text-field w-input',
                'placeholder': 'eg. moshfequr rahman',
                'required': True
            }),
            'email': forms.EmailInput(attrs={
                'class': 'text-field w-input',
                'placeholder': 'eg. email@gmail.com',
                'required': True
            }),
            'designation': forms.TextInput(attrs={
                'class': 'text-field w-input',
                'placeholder': 'eg. Webflow developer'
            }),
            'bio': forms.TextInput(attrs={
                'class': 'text-field w-input',
                'placeholder': 'eg. google.com'
            }),
            'source_bio': forms.TextInput(attrs={
                'class': 'text-field w-input',
                'placeholder': 'eg. Why this source is important?'
            }),
        }

users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import DetailView
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import View, ListView, UpdateView

from skillbook_app.models import Post, PostCategory
from .forms import UserCreationForm, ProfileForm
from .models import Profile, UserProfile


class SignInView(View):
    def get(self, *args, **kwargs):
        template = 'users/signin.html'
        return render(self.request, template)

    def post(self, *args, **kwargs):
        email = self.request.POST['email']
        password = self.request.POST['password']
        user = authenticate(email=email, password=password)
        if user is not None:
            if user.is_active:
                login(self.request, user)
                messages.info(self.request, "Welcome {}.".format(user.name))
                return redirect('home')
        else:
            messages.warning(self.request, "Your email or password is not correct.")
            return redirect('users:signin')


class SignUpView(View):
    def get(self, *args, **kwargs):
        context = {
            'form': UserCreationForm
        }
        template = 'users/signup.html'
        return render(self.request, template, context)

    def post(self, *args, **kwargs):
        form = UserCreationForm(self.request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            Profile.objects.create(
                user=user,
                name=user.name,
                email=user.email
            )
            login(self.request, user)
            messages.info(self.request, "Welcome {}.".format(user.name))
            return redirect('home')
        messages.warning(self.request, "Your password does not matching or account already exist.")
        return redirect('users:signup')


class ProfileDetailView(DetailView):
    model = Profile
    context_object_name = 'profile'
    template_name = 'users/profile.html'


class EditProfileView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'users/edit_profile.html'
    success_message = 'Successfully updated your profile.'

    def form_valid(self, form):
        profile = form.save(commit=False)
        user = self.request.user
        if user.email != profile.email:
            if UserProfile.objects.filter(email=profile.email).exists():
                messages.warning(self.request, "Your can not use this email cz this account already exist.")
                return redirect('users:edit-profile')

        user.name = profile.name
        user.email = profile.email
        user.save()
        return super().form_valid(form)

    # def get(self, *args, **kwargs):
    #     profile = Profile.objects.get(user=self.request.user)
    #     form = ProfileForm(instance=profile)
    #     context = {
    #         'form': form
    #     }
    #     template = 'users/edit_profile.html'
    #     return render(self.request, template, context)
    #
    # def post(self, *args, **kwargs):
    #     form = ProfileForm(self.request.POST, self.request.FILES)
    #     if form.is_valid():
    #         profile = form.save(commit=False)
    #         user = self.request.user
    #         if user.email != profile.email:
    #             if UserProfile.objects.filter(email=profile.email).exists():
    #                 messages.warning(self.request, "Your can not use this email cz this account already exist.")
    #                 return redirect('users:edit-profile')
    #
    #         userProfile = Profile.objects.get(user=user)
    #         userProfile.name = profile.name
    #         user.name = profile.name
    #         userProfile.email = profile.email
    #         user.email = profile.email
    #         userProfile.designation = profile.designation
    #         userProfile.bio = profile.bio
    #         userProfile.source_bio = profile.source_bio
    #         userProfile.image = profile.image
    #         userProfile.save()
    #         user.save()
    #         messages.info(self.request, "Updated your profile.")
    #         return redirect('home')
    #     messages.info(self.request, "Your profile data is not valid.")
    #     return redirect('users:edit-profile')


class ProfileListView(ListView):
    model = Profile
    context_object_name = 'curators_list'
    template_name = 'users/curators_list.html'


class ProfileWiseLikedPostView(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = 'liked_post_list'
    template_name = 'posts/liked_post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = PostCategory.objects.all()
        return context

    def get_queryset(self):
        queryset = self.request.user.profile.liked_posts.all()
        return queryset

templates/users/curators_list.html
{% extends 'base.html' %}
<title>{% block title %}Curators{% endblock %}</title>
{% block content %}
    {% include 'curators.html' %}
    {% include 'subscribe.html' %}
{% endblock %}

templates/users/edit_profile.html
{% extends 'base.html' %}
<title>{% block title %}Edit Profile{% endblock %}</title>
{% block content %}
  <div class="wrap">
    <div class="div-block">
      <h1 class="title">Edit your profile</h1>
      <div class="form-block-2 w-form">
        <form id="form" name="form" data-name="Profile Form" action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="name" class="field-label">Name</label>
            {{ form.name }}
            <label for="email" class="field-label">Email</label>
            {{ form.email }}
            <label for="designation" class="field-label">Designation</label>
            {{ form.designation }}
            <label for="bio" class="field-label">Bio</label>
            {{ form.bio }}
            <label for="source_bio" class="field-label">Source Bio</label>
            {{ form.source_bio }}
            <label for="image" class="field-label">Upload photo</label>
            {{ form.image }}
            <br>
            <br>
            <br>
            <button type="submit" data-wait="Please wait..." class="submit-button-2 w-button">Save</button>
        </form>
        <div class="w-form-done">
          <div>Thank you! Your submission has been received!</div>
        </div>
        <div class="w-form-fail">
          <div>Oops! Something went wrong while submitting the form.</div>
        </div>
      </div>
    </div>
  </div>
  {% include 'subscribe.html' %}
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
<title>{% block title %}Profile{% endblock %}</title>
{% block content %}
{% load static %}
{% get_media_prefix as MEDIA_URL %}
<div class="wrap">
    <div class="div-block">
        {% if profile.image %}
            <img src="{{ profile.image.url }}" alt="" class="profile-avator">
        {% else %}
            <img src="{% static 'images/Unknown.png' %}" alt="" class="profile-avator">
        {% endif %}
      <h1 class="title">{{ profile.name }}</h1>
      <p class="paragraph-2">{{ profile.designation }}</p>
      <div class="div-block-2">
        <h3 class="sub-head">{{ profile.bio }}
            <a href="https://spreadshare.co/stream/133"><br></a>
        </h3>
        <div class="counts">
          <h3 class="sub-head">{{ profile.posts.all.count }}
              <span class="text-span">posts</span>
              <a href="https://spreadshare.co/stream/133"><br></a>
          </h3>
          <h3 class="sub-head">{{ profile.liked_posts.all.count }}
              <span class="text-span">liked post</span>
              <a href="https://spreadshare.co/stream/133"><br></a>
          </h3>
        </div>
      </div>
    </div>
    <h1 class="title-copy">Your own posts:</h1>
    <div class="collection">
      {% if profile.posts.all %}
          {% for post in profile.posts.all %}
              <div class="collection-item">
                  <a href="{{ post.source_link }}" target="_blank">
                      <img src="{{ MEDIA_URL }}{{ post.image }}" sizes="(max-width: 479px) 29vw, (max-width: 991px) 30vw, 290.390625px" alt="" class="post_img">
                  </a>
                <h2 class="post_title">{{ post.title }}<br></h2>
                <p class="post_desc">
                    {{ post.content|truncatechars:200 }}
                </p>
                {% if request.user.profile in post.liked.all %}
                    <a href="{% url 'posts:remove_from_like' post.pk %}">
                      <img src="{% static 'images/heart.png' %}" alt="" class="like_icon">
                    </a>
                {% else %}
                    <a href="{% url 'posts:add_to_like' post.pk %}">
                      <img src="{% static 'images/heart.svg' %}" alt="" class="like_icon">
                    </a>
                {% endif %}
              {% if request.user.profile == profile %}
                  <a class="submit-button-2 w-button" href="{% url 'posts:post_update' post.id %}">Update</a>
                      <br>
                  <a class="submit-button-2 w-button" href="{% url 'posts:post_delete' post.id %}">Delete</a>
              {% endif %}
                  <br>
              <a class="submit-button-2 w-button" href="{{ post.file.url }}">Download File</a>
              </div>
          {% endfor %}
      {% else %}
          <div class="collection-item">
            <h2 class="post_title">You have no own post.<br></h2>
          </div>
      {% endif %}
    </div>
    <h1 class="title-copy">Your liked posts:</h1>
    <div class="collection">
      {% if profile.liked_posts.all %}
          {% for post in profile.liked_posts.all %}
              <div class="collection-item">
                <a href="{{ post.source_link }}" target="_blank">
                      <img src="{{ MEDIA_URL }}{{ post.image }}" sizes="(max-width: 479px) 29vw, (max-width: 991px) 30vw, 290.390625px" alt="" class="post_img">
                  </a>
                <h2 class="post_title">{{ post.title }}<br></h2>
                <p class="post_desc">
                    {{ post.content|truncatechars:200 }}
                </p>
                {% if request.user.profile in post.liked.all %}
                    <a href="{% url 'posts:remove_from_like' post.pk %}">
                      <img src="{% static 'images/heart.png' %}" alt="" class="like_icon">
                    </a>
                {% else %}
                    <a href="{% url 'posts:add_to_like' post.pk %}">
                      <img src="{% static 'images/heart.svg' %}" alt="" class="like_icon">
                    </a>
                {% endif %}
                <a class="submit-button-2 w-button" href="{{ post.file.url }}">Download File</a>
              </div>
          {% endfor %}
      {% else %}
          <div class="collection-item">
            <h2 class="post_title">You have no liked post.<br></h2>
          </div>
      {% endif %}
    </div>
  </div>
  {% include 'subscribe.html' %}
{% endblock %}

templates/users/signin.html
{% extends 'base.html' %}
<title>{% block title %}Sign In{% endblock %}</title>
{% block content %}
  <div class="wrap">
    <div class="div-block">
      <h1 class="title">Sign in to your account</h1>
      <h3 class="sub-head">
          Use the below form to sign in
          <a href="https://spreadshare.co/stream/133"><br></a>
      </h3>
      <div class="form-block-2 w-form">
        <form id="form" name="form" data-name="SignIn Form" action="." method="post">
            {% csrf_token %}
            <label for="email" class="field-label">Email Address</label>
            <input type="email" class="text-field w-input" name="email" data-name="Email" placeholder="eg. email@gmail.com" id="email" required="">
            <label for="password" class="field-label">Password</label>
            <input type="password" class="text-field w-input" name="password" data-name="Password" placeholder="eg. ******&#x27;" id="password" required="">
            <button type="submit" data-wait="Please wait..." class="submit-button-2 w-button">Sign In</button>
        </form>
        <div class="w-form-done">
          <div>Thank you! Your submission has been received!</div>
        </div>
        <div class="w-form-fail">
          <div>Oops! Something went wrong while submitting the form.</div>
        </div>
      </div>
    </div>
  </div>
  {% include 'subscribe.html' %}
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}
<title>{% block title %}Sign Up{% endblock %}</title>
{% block content %}
  <div class="wrap">
    <div class="div-block">
      <h1 class="title">Sign up for an account</h1>
      <h3 class="sub-head">
          Use the below form to sign up
          <a href="https://spreadshare.co/stream/133"><br></a>
      </h3>
      <div class="form-block-2 w-form">
        <form id="form" name="form" data-name="SignUp Form" action="." method="post">
            {% csrf_token %}
            <label for="name" class="field-label">Your Name</label>
            {{ form.name }}
            <label for="email" class="field-label">Email Address</label>
            {{ form.email }}
            <label for="password1" class="field-label">Password</label>
            {{ form.password1 }}
            <label for="password2" class="field-label">Password Confirmation</label>
            {{ form.password2 }}
            <button type="submit" data-wait="Please wait..." class="submit-button-2 w-button">Sign Up</button>
        </form>
        <div class="w-form-done">
          <div>Thank you! Your submission has been received!</div>
        </div>
        <div class="w-form-fail">
          <div>Oops! Something went wrong while submitting the form.</div>
        </div>
      </div>
    </div>
  </div>
  {% include 'subscribe.html' %}
{% endblock %}